spring.application.name=sanctuary-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/sanctuary
spring.datasource.username=sanctuary
spring.datasource.password=sanctuary
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration